# Generated by Django 6.1 on 2026-08-25 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('original_filename', models.CharField(max_length=255)),
                ('original_file', models.FileField(upload_to='datasets/originals/')),
                ('working_file', models.FileField(blank=True, upload_to='datasets/working/')),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('column_count', models.PositiveIntegerField(default=0)),
                ('columns_meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CleaningStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('drop_nulls', 'Drop rows with nulls'), ('fill_nulls', 'Fill nulls'), ('drop_column', 'Drop column'), ('encode_categorical', 'Encode categorical column'), ('scale_numeric', 'Scale numeric column'), ('rename_column', 'Rename column'), ('cast_dtype', 'Cast column dtype')], max_length=30)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='comparator.dataset')),
            ],
            options={
                'ordering': ['applied_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelComparisonRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_column', models.CharField(max_length=255)),
                ('feature_columns', models.JSONField(default=list)),
                ('task_type', models.CharField(choices=[('regression', 'Regression'), ('classification', 'Classification')], max_length=20)),
                ('results', models.JSONField(blank=True, default=dict)),
                ('best_model_name', models.CharField(blank=True, max_length=100)),
                ('best_model_file', models.FileField(blank=True, null=True, upload_to='models_saved/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_runs', to='comparator.dataset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
